name: default

on: [push]

jobs:
  build:

    runs-on: windows-latest
        
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          setlocal
          python -m pip install --upgrade pip
          pip install -r Coingecko_Automation\requirements.txt
          PYTHONPATH = Coingecko_Automation
      - name: Test with behave
        run: behave Coingecko_Automation\tests